USE ARTICULOS_slug;
DROP TABLE IF EXISTS ARTICULOS;

CREATE TABLE ARTICULOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50),
    CONTENIDO VARCHAR(250),
    FECHA DATE
);

INSERT INTO ARTICULOS (TITULO, CONTENIDO, FECHA) VALUES ('cajita', 'lapices', '2023-12-12');
