USE ARTICULOS_slug;
DROP TABLE IF EXISTS ARTICULOS;

CREATE TABLE ARTICULOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50),
    CONTENIDO VARCHAR(250),
    FECHA DATE,
    slug VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO ARTICULOS (TITULO, CONTENIDO, FECHA, slug) VALUES ('cajita', 'lapices', '2023-12-12', 'cajita');
