-- Contiene las tablas necesarias, para luego lanzar el script en la terminal

CREATE TABLE RESULTADOS(
    ID INT NOT NULL AUTO_INCREMENT,
    PAIS VARCHAR(255) NOT NULL,
    RESULTADO_TIPO VARCHAR(255) NOT NULL,
    RESULTADO_VALOR INT NOT NULL,
    PRIMARY KEY (ID)
);

/*He decidido poner los resultados como en futbol entonces RESULTADO_VALOR de tipo INT no me sirve*/
ALTER TABLE RESULTADOS MODIFY RESULTADO_VALOR VARCHAR(255);

INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Honduras', 'Victoria', '60-40');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('España', 'Victoria', '30-20');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Francia', 'Derrota', '25-28');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Italia', 'Empate', '15-15');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Brasil', 'Victoria', '45-30');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Alemania', 'Derrota', '10-20');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Argentina', 'Empate', '22-22');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('México', 'Victoria', '60-50');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Canadá', 'Derrota', '18-24');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Rusia', 'Victoria', '33-27');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('China', 'Empate', '11-11');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('India', 'Victoria', '40-38');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Japón', 'Derrota', '30-45');
INSERT INTO RESULTADOS (PAIS, RESULTADO_TIPO, RESULTADO_VALOR) VALUES ('Sudáfrica', 'Victoria', '29-20');
