# Generated by Django 5.0.6 on 2024-06-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DescubrimientoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conocimiento',
            new_name='Descubrimiento',
        ),
    ]
